language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: ./linked_list_tests.py; ./stack_tests.py; ./queue_tests.py; hash_table_tests.py